export enum Features {
  FINANCIAL_DASHBOARD = "FINANCIAL_DASHBOARD",
  SALES_REPORTS = "SALES_REPORTS",
  UPLOAD_PRODUCTS_EXCEL = "UPLOAD_PRODUCTS_EXCEL",
  CUSTOMER_MANAGEMENT = "CUSTOMER_MANAGEMENT",
}
